### ISSUE TITLE
TODO: redirect-lister functionality improvement.

### ISSUE THREAD

**Issue by oz9un** [oz9un/redirect-lister#1]
- [ ] Add a screenshot of the tool while it is working in CLI, (fror README).
- [ ] Make outputs more fancy! (Some output colorization libraries can be used).
- [ ] Add an option for setting timeout between each requests (with -t argument). Should be settable in milliseconds.
- [ ]  Also check for more than one redirections and also list them in CSV file with proper format. Like creating new column for each redirection.
